import express from 'express';
import upload from '../../service/Cloudinary/upload.js';
import { isAdmin } from '../../middlewares/admin.middlewares.js';
const subboardRoute = express.Router({ mergeParams: true });
subboardRoute.use(express.json());
import {addBoard, updateSubBoard, deleteSubBoard, uploadFileImg} from './subboard.controller.js';
subboardRoute.post("/tasks/:taskId/subboards",isAdmin, addBoard);
subboardRoute.patch("/subboards/:idSB", isAdmin, updateSubBoard);
subboardRoute.delete("/subboards/:idSB", isAdmin, deleteSubBoard);
subboardRoute.post("/subboards/:idSB/upload", isAdmin, upload.single('background'), uploadFileImg);
export default subboardRoute;